### ISSUE TITLE
SiteSupervisor complains about EO.WebBrowser License

### ISSUE THREAD

**Issue by Ginscoe** [bizspeed/bizspeed.github.io#1]
Trips -> Orders -> Edit Fuel Order -> Map View

Version: 2017.8.25.1443

**Comment by mrbelk** [comment]
Can you re-create this in the BizSpeed/MobileHub repository?

________________________
Matthew Belk
ph. 678-287-3315

**Comment by Ginscoe** [comment]
Am I a member?  I couldn't see where to do it.

**Comment by mrbelk** [comment]
you should be able to do it now. Closing this issue...
